GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "react",
  "author": "max",
  "url": "http@1234.com",
  "likes": "2",
  "userId" : "64fc7dcf711bdf38e84caeed"
}
###
POST http://localhost:3001/api/testing/reset
Content-Type: application/json
###
GET http://localhost:3003/api/blogs/65970d9d08ed541416f07deb
