GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "react",
  "author": "max",
  "url": "http@1234.com",
  "likes": "2",
  "userId" : "64fc7dcf711bdf38e84caeed"
}