
POST http://localhost:3003/api/users
Content-Type : application/json

{
     "name": "Venla Ruuska",
     "userName": "Venla",
     "password": "Xyz@123456"
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/login
Content-Type : application/json

{
    "name"     : "Arto Hellas",
    "userName"   : "Arto",
    "password" : "Xyz@123456"
}
###
GET http://localhost:3003/api/users/653aa558f7fb9da4096c0eb2