
POST http://localhost:3003/api/login
Content-Type : application/json

{
     "name": "Tofgfgf",
            "userName": "Dadfdfdf",
            "password": "Xyz@123456"
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/login
Content-Type : application/json

{
    "name"     : "Tony",
    "userName"   : "David",
    "password" : "Xyz@123456"
}